name: institute_management
description: Institute Management - Students, Fees, Income/Expense, Marks & Reports
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.66.0
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
